### ISSUE TITLE
Unable to edit the file after mounting the cephFs on windows using ceph-dokan

### ISSUE THREAD

**Issue by mayuripriya12** [cloudbase/ceph-windows-installer#20]
Hi all,

I am very new to ceph. I have set up my cluster and tried to mount the ceph file system(CephFS) on linux and windows using ceph dokan.
I was able to mount the file system in both the OS. But in windows I can only read the file. I am unable to edit the file in windows while in linux edit works perfectly fine.

Note I mounted CephFS  using a client keyring who has the read and write permissions.
While editing the file in windows i get the below error message.

![image](https://user-images.githubusercontent.com/75684402/150335515-97bfe203-7dca-48df-8f6d-c827f5431795.png)

Has anyone know about this issue. It would be a great help. Thanks in advance.

Best Regards,
Mayuri Priya

**Comment by petrutlucian94** [comment]
Hi,

It's probably because of the Ceph file permissions. You may either disable client side permissions or mount the share using a different ``uid``/``gitd``. Add the following section to your Windows ``ceph.conf`` file and update it as needed:

```
[client]
# client_permissions = false
# client_mount_uid = 1000
# client_mount_gid = 1000
```

Regards,
Lucian

**Comment by petrutlucian94** [comment]
I'm going to close the issue for now, please let us know if the issue persists after addressing the cephfs permissions.
