### ISSUE TITLE
rdb.exe not working on new install

### ISSUE THREAD

**Issue by AxisNL** [cloudbase/ceph-windows-installer#27]
Hey, don't know if this is the right place. If not, I hope you guys and girls can point me in the right direction. I've setup my first ceph pacific cluster, and started mounting some rbd images, works like a charm.

But now I want to mount some rbd images on my windows boxes as well, but I'm getting really obscure error messages:

I basicly did a clean install of Win2019, gave it a nic in the right vlan, (my ceph client network uses slaac), put the ceph.conf in, and the keyring. If I do a rbd.exe ls (or other commands) I get errors like these:

```
C:\Program Files\Ceph\bin>rbd.exe ls
../src/msg/msg_types.h: In function 'void entity_addr_t::set_port(int)' thread 5 time 2022-07-21T01:44:35.391139Venezuela Standard Time
../src/msg/msg_types.h: 364: ceph_abort_msg("abort() called")
 ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)
2022-07-21T01:44:35.391Venezuela Standard Time 5 -1 ../src/msg/msg_types.h: In function 'void entity_addr_t::set_port(int)' thread 5 time 2022-07-21T01:44:35.391139Venezuela Standard Time
../src/msg/msg_types.h: 364: ceph_abort_msg("abort() called")

 ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)
```
ceph.conf
```
[global]
    fsid = 73f9bf2a-0631-11ed-86ef-3fccd747cc32
    mon_host = fd00:85:c:100::198
    log to stderr = true
    run dir = C:/ProgramData/ceph/out
    crash dir = C:/ProgramData/ceph/out
[client]
    keyring = C:/ProgramData/ceph/ceph.client.admin.keyring
    admin socket = C:/ProgramData/ceph/out/$name.$pid.asok
```
Any ideas?

**Comment by petrutlucian94** [comment]
Hi,

Thanks for reporting this issue. The Pacific release doesn't support ipv6 but fortunately there's a backport that's likely going to merge soon: https://github.com/ceph/ceph/pull/47303.

There are a few other fixes that we'd like to include before releasing new Pacific and Quincy MSIs. I'm seeing increased demand for the ipv6 fix, so we'll try to speed things up.

PS: sorry for the late reply.

Regards,
Lucian

**Comment by petrutlucian94** [comment]
We've just released updated Pacific and Quincy MSIs that include the IPv6 fix along with a few other important fixes: https://cloudbase.it/ceph-for-windows/

Please give it a try and let me know how it went.

**Comment by petrutlucian94** [comment]
Closing the issue since the bug fix was merged and new MSIs have been released.
