### ISSUE TITLE
Feature: Optional case-insensitive mounts

### ISSUE THREAD

**Issue by deepfire** [cloudbase/ceph-windows-installer#32]
Quite some WIndows software assumes that the underlying filesystem is case-insensitive.

> Aside: specifically this means, that software would expect a file originally created as `FooBar` to be also accessible as `foobar` and `FOOBAR` and any other case permutation.

When that assumption is broken, obvious consequences follow.

It would be, therefore, rather useful to have `ceph-dokan` provide a case-insensitive mount option.

To that end, https://dokan-dev.github.io/dokany-doc/html/group___d_o_k_a_n___o_p_t_i_o_n.html even lists an apparently relevant-sounding flag: `DOKAN_OPTION_CASE_SENSITIVE` -- although what exactly its semantics are is unclear to me.

At worst, I can imagine that might require implementation of this functionality at Ceph level..

P.S. If this issue is misplaced -- please say so, and I'll move it to the ceph repository.  Filed it here on the assumption that the primary development point for `ceph-dokan` is Cloudbase.

**Comment by petrutlucian94** [comment]
Thanks for opening this issue. Feel free to use this Github repo for Windows related issues, it's more visible to us than the official ceph tracker (https://tracker.ceph.com).

About case insensitive mounts: it's a bit more complicated. ceph-dokan is simply forwarding requests to cephfs, which is case sensitive. A proper implementation would require significant cephfs changes.

A simple solution would be to convert everything to lower case on the client side (Samba can also do that - ``preserve_case = no`` and ``default case = lower``. There are a few issues though:

* it wouldn't preserve casing (Later edit: we could store the original casing using extended attributes, apparently other projects had the same issue)
* we might have some name collisions (e.g. existing ``Test`` file and a Windows ``test`` file), some implementations would just convert it to ``test~1``
* the extra lookups might involve some overhead

If a shared filesystem isn't required, another option would be to just use NTFS on top of RBD.

We're also working on CSV support (an experimental implementation might be included in the following Ceph release: https://github.com/ceph/ceph/pull/48631), which would allow you to use Windows Scale-Out File Servers on top of RBD).

**Comment by deepfire** [comment]
@petrutlucian94, thank you for your response!

I would suggest that in many cases, at least when the data is used by Windows clients only, the case preservation might not even be necessary.

So, as a first iteration, the very basic option of providing optional case normalisation on the client side -- sounds rather useful.

It would certainly satisfy my use case.

NTFS over RBD, on the other hand, has an additional downside -- it is bound to cause read/write amplification, and therefore lose performance.

**Comment by petrutlucian94** [comment]
I've submitted a PR: https://github.com/ceph/ceph/pull/53456

About NTFS over RBD, I suggest running some benchmarks (e.g. fio). We got comparable results.

**Comment by deepfire** [comment]
@petrutlucian94, thank you for working on it!

Is it possible to get a preview build of the installer?  Or, otherwise, when could one be expected?

**Comment by petrutlucian94** [comment]
@deepfire sure, here's a preview build: https://cloudbase.it/downloads/ceph_dev_case_insensitive.msi

Let me know how it works. We'll most probably include it in the upcoming S release.

**Comment by deepfire** [comment]
@petrutlucian94, Thank you!

This is what I'm getting:

- invocation `ceph-dokan.exe --conf ceph.conf -l i --name client --client_fs store --root-path / --case-insensitive`
- immediate error: `libc++abi: terminating due to uncaught exception of type std::runtime_error: invalid utf8`
- `--force-lowercase` doesn't make a difference to the outcome
- `--case-insensitive` doesn't make a difference to the outcome

**Comment by deepfire** [comment]
This is what I've been able to find on the topic:

- https://perl11.org/blog/foldcase.html
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/fs/unicode/utf8-core.c (with the callers being, notably, in https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/fs/libfs.c ) -- although, admittedly, the kernel bits are more likely to be useful within Ceph itself, rather than the client side
- https://lwn.net/Articles/784124/ (old)
- most recent casefolding implementation for a Linux FS (using the generic API) I'm aware of: https://www.phoronix.com/news/Bcachefs-Case-Folding-Patches -- from Michael's description that uses the downcasing approach

**Comment by petrutlucian94** [comment]
@deepfire you'll probably need this: https://github.com/ceph/ceph/pull/53291, it crashes when logging unicode characters.

I'll apply that fix and provide an updated MSI later today.

**Comment by petrutlucian94** [comment]
I've updated the MSI, same url: https://cloudbase.it/downloads/ceph_dev_case_insensitive.msi

**Comment by deepfire** [comment]
@petrutlucian94, looks good after initial testing, thank you!

More extensive testing underway.

**Comment by petrutlucian94** [comment]
The upstream PR has merged and the feature will be available in the upcoming Ceph release. Thanks again for bringing this up and for testing our proposed implementation.

I'll go ahead and close this issue.
